study_window:
  end_date: '2020-05-13'
study_fips:
- '06001'
- '06037'
- 06059
- '06075'
- 06081
- 06085
- '17031'
- '17043'
- '17089'
- '17097'
- '17111'
- '17197'
- '18089'
- '22051'
- '22071'
- '22075'
- '22087'
- '22103'
- '26099'
- '26125'
- '26163'
- '36005'
- '36047'
- '36061'
- '36081'
- '36085'
- '53033'
- '53061'
rwj:
  rwj_var:
  - statecode
  - countycode
  - fipscode
  - state
  - county
  - year
  - county_ranked
  - v001_rawvalue
  - v002_rawvalue
  - v037_rawvalue
  - v009_rawvalue
  - v011_rawvalue
  - v004_rawvalue
  - v004_other_data_1
  - v005_rawvalue
  - v155_rawvalue
  - v021_rawvalue
  - v069_rawvalue
  - v023_rawvalue
  - v044_rawvalue
  - v140_rawvalue
  - v125_rawvalue
  - v124_rawvalue
  - v136_rawvalue
  - v136_other_data_1
  - v147_rawvalue
  - v060_rawvalue
  - v003_rawvalue
  - v063_rawvalue
  - v065_rawvalue
  - v141_rawvalue
  - v142_rawvalue
  - v153_rawvalue
  - v154_rawvalue
  - v051_rawvalue
  - v052_rawvalue
  - v053_rawvalue
  - v059_rawvalue
  - v057_rawvalue
  roche_names:
  - statecode
  - countycode
  - fips
  - state
  - county
  - year
  - county_ranked
  - premature_death_v001
  - poor_or_fair_health_v002
  - low_birthweight_v037
  - adult_smoking_v009
  - adult_obesity_v011
  - primary_care_physicians_v004
  - ratio_population_to_pcp_v004
  - preventable_hospital_stays_v005
  - flu_vaccination_v155
  - education_high_school_v021
  - education_some_college_v069
  - unemployment_v023
  - income_inequality_v044
  - social_association_v140
  - air_pollution_parti_matter_v125
  - drinking_water_violation_v124
  - severe_housing_problem_v136
  - high_housing_cost_household_pct_v136
  - life_expectancy_v147
  - disease_diabetes_prevalence_v060
  - uninsured_adult_v003
  - median_household_income_v063
  - children_eligible_free_lunch_v065
  - resid_segregat_black_white_v141
  - resid_segregat_nonwhite_white_v142
  - home_ownership_v153
  - severe_housing_cost_burden_v154
  - population_v051
  - age_below_18_pct_v052
  - age_above_65_pct_v053
  - not_proficient_english_pct_v059
  - gender_female_pct_v057
  column_index:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 34
  - 49
  - 70
  - 75
  - 135
  - 140
  - 153
  - 173
  - 183
  - 188
  - 193
  - 218
  - 228
  - 258
  - 263
  - 268
  - 273
  - 307
  - 397
  - 462
  - 503
  - 523
  - 528
  - 533
  - 611
  - 616
  - 621
  - 626
  - 631
  - 666
  - 671
pca_variables:
  vars:
  - premature_death_v001
  - poor_or_fair_health_v002
  - low_birthweight_v037
  - adult_smoking_v009
  - adult_obesity_v011
  - primary_care_physicians_v004
  - ratio_population_to_pcp_v004
  - preventable_hospital_stays_v005
  - flu_vaccination_v155
  - education_high_school_v021
  - education_some_college_v069
  - unemployment_v023
  - income_inequality_v044
  - social_association_v140
  - air_pollution_parti_matter_v125
  - drinking_water_violation_v124
  - severe_housing_problem_v136
  - high_housing_cost_household_pct_v136
  - life_expectancy_v147
  - disease_diabetes_prevalence_v060
  - uninsured_adult_v003
  - median_household_income_v063
  - children_eligible_free_lunch_v065
  - resid_segregat_black_white_v141
  - resid_segregat_nonwhite_white_v142
  - home_ownership_v153
  - severe_housing_cost_burden_v154
  - age_below_18_pct_v052
  - age_above_65_pct_v053
  - not_proficient_english_pct_v059
  - gender_female_pct_v057
  - cancer_age_adjusted_rate
  - copd_prevalence
  - hypertension_prevalence
  - ami_prevalence
